title: Marco Zaplan
tagline: Critical minerals, just energy transition, and open data consultant.
description: >-
  Independent consulting and research on natural resource governance,
  open data, and public financial management.
author: Marco Zaplan
email: marcozaplan@gmail.com

url: "https://marcozaplan.github.io"
baseurl: ""

links:
  - name: Email
    url: "marcozaplan@gmail.com"
  - name: LinkedIn
    url: "https://www.linkedin.com/in/marco-zaplan-69212583/"
  - name: GitHub
    url: "https://github.com/marcozaplan"

permalink: /blog/:year/:month/:title/
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
